#!/usr/bin/env node

function echoWithColor(color, message) {
	console.log(color + message + "\x1b[0m");
}

const blue = (message) => echoWithColor("\x1b[34m", message);

const args = process.argv.slice(2);

blue(`running 'a' with ${args} in JS in blue`);
